# Generated by Django 4.2 on 2023-04-12 10:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("song_line", models.TextField()),
                ("description", models.TextField()),
                (
                    "gallery_image",
                    models.ImageField(
                        null=True, upload_to=app.models.city_image_file_path
                    ),
                ),
                ("drive_url", models.URLField()),
            ],
        ),
    ]
