# Generated by Django 4.2 on 2023-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_city_gallery_image_cityimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="drive_url",
            field=models.URLField(null=True),
        ),
    ]
